### ISSUE TITLE
First name is picked up as a nickname

### ISSUE THREAD

**Issue by Molodax** [costastf/locationsharinglib#10]
First name from the full name of a person is picked up as a nickname which is incorrect.

**Comment by costastf** [comment]
I cannot reproduce this and I have not had any other reports of this. Could you please check you google account and make sure that everything is in the place that is should be  and report back with some more details on this?

**Comment by Molodax** [comment]
I would be happy to provide you with further details, just not sure what kind of details are missing?
My nickname is specified in my Google+ profile as well as my full name, however, the component picks up my first name as a nickname using your library.
I use your library in conjunction with the Homeassistant component https://github.com/home-assistant/home-assistant/pull/12301

**Comment by costastf** [comment]
This component does not interface with google+ at all. Could you check how your account shows up in google maps and if it is correct there?

**Comment by Molodax** [comment]
I mentioned Google+ because it is the only place where you can enter your Google account nickname and your library has attribute of nickname. Google maps shows only full name and have no option of nickname. Perhaps, there is some inconsistency within Google services for the same account, so I can close the issue in such case.

**Comment by costastf** [comment]
My guess is that there is some inconsistency and since I see no way to fix this since I am parsing the output of the maps response and it seems consistent for everyone as far as maps is concerned I think this can be closed.
