### ISSUE TITLE
Alternative to mapscookiegettercli?

### ISSUE THREAD

**Issue by zefoo** [costastf/locationsharinglib#101]
Howdy, is there an alternative to https://pypi.org/project/mapscookiegettercli/ ? Since it seems it was archived.

Essentially trying to get a cookie via CLI without having to open browser. :) 

I can code something if there isn't an alternative but thought I'd ask just in case. Thank you for this library!

**Comment by costastf** [comment]
Hi there, happy new year! Not something from me. Google has many different systems around the globe and keeping up with all of them was a very big hustle that was not worth the trouble. I hope there are parts that are useful to you and they help you get started.

**Comment by backupandforkacc** [comment]
I also tested some stuff, but nothing seems to work.
@zefoo : Did you find a solution?

**Comment by costastf** [comment]
Hey guys, I guess we can close this?

**Comment by zefoo** [comment]
I didn't find anything. I'm having an issue with Google's cookie not persisting. I save the cookie in Firefox, then close the browser (I don't usually use Firefox). It works for a little but eventually stopped (it's done this several times now). My next step was to try to automate something with CLI and/or Selenium to save the cookies but I haven't got around to it (doing some work with a non-profit to help them track folks). 

From what I believe @costastf has said before, the cookie should persist and doesn't expire. So it's possible I'm not doing something correctly although I think I am.

**Comment by costastf** [comment]
@zefoo if you are using the google suite and there are admin settings that might make a cookie expire. If you are on a personal google account they should not expire. Shall we close this issue?

**Comment by costastf** [comment]
I am closing this as it was mostly informational and there is no progress on it.
