### ISSUE TITLE
duplicate authentication check

### ISSUE THREAD

**Issue by stevedonnelly** [costastf/locationsharinglib#102]
https://github.com/costastf/locationsharinglib/blob/29531064e80354a8295cb4ba7dd2ab6842bb551a/locationsharinglib/locationsharinglib.py#L105

I'm guessing this authentication check was duplicated by accident?

**Comment by costastf** [comment]
No, not really, we visit the account url once to get the cookies from that page and then we revisit and check the final info to check that everything works. Or something to that effect, it has been 6 years.... ☺️

**Comment by costastf** [comment]
Don't recall all the details but the debug logs kinda explain.

**Comment by costastf** [comment]
@stevedonnelly I will be closing this as I hope I have answered your question.
