### ISSUE TITLE
Feature: Include Timezone as Field

### ISSUE THREAD

**Issue by Bijan-A** [costastf/locationsharinglib#108]
Would there be any possibility of including the users timezone as one of the fields?

I am currently able to implement this myself by doing:

    from tzwhere import tzwhere
    user = service.get_coordinates_by_nickname('USER')
    tz = tzwhere.tzwhere()
    timezoneName = tz.tzNameAt(user.latitude, user.longitude) # Returns "America/Los_Angeles"

**Comment by costastf** [comment]
Hi @Abolfazl , although i think this is a nice improvement, i would not want to bring in more dependencies, especially one that would bring in numpy just for a very small feature like this. I think it would be better to implement this client side like you did. Thoughts?

**Comment by Bijan-A** [comment]
Yes that is true. I can continue to implement it client side
