### ISSUE TITLE
No more country code?

### ISSUE THREAD

**Issue by TilmanGuenther** [costastf/locationsharinglib#116]
Not sure if this is a fixable problem or if this is something Google broke, but the data for "country_code" now always returns "None" rather than an actual country code. 

My test code:

```
...
def publish(client):
    while True:
        time.sleep(update_interval)
        for person in service.get_all_people():
            for data in dir(person):
                if not data.startswith('_'):
                    print(topic + person.nickname + "/" + data, str(getattr(person, data)))
                    client.publish(topic + person.nickname + "/" + data, str(getattr(person, data)))
...
```

**Comment by costastf** [comment]
Hi @TilmanGuenther , that indeed seems to be the case, as in Google sends a None where the country code data used to be, at least in my location. I know that there is localization so it might not be true everywhere but it is true in your case and mine at least. Also indeed, nothing can be done about that, if there is no data it just is what it is. :(
