### ISSUE TITLE
Issue with some accounts

### ISSUE THREAD

**Issue by pixeye33** [costastf/locationsharinglib#13]
Hello,

I'm setting this for my home assistant installation, the bug i'm having is probably not related to home assistant implementation.

I have 3 google accounts : A, B and C.
A shares its location to B and C.

When i use this library with B account : no problem
When i use this library with C account : here is what i got

`2018-04-07 19:01:24 ERROR (SyncWorker_4) [locationsharinglib.Service] Response: [None, None, '0ahUKXXXXXXXXXXXXXXXZABCAE', 'ZPnXXXXXXXXXXXXXXXM', None, None, 'CNzzo9YFEXXXXXXXXXXXXXXXiPTej1Wi+jUMNTYVBYXdS0KXXXXXXXXXXXXXXXktIgY6juslw==', 1800, 1523120484424, [-869868227, [None, [None, -0.856X868, 43.855X333], 1523120352491, 12, '10 Rue tulipes, 53400 Awesome, France', None, 'FR', 7200000]], None, [0]] Traceback (most recent call last): File "/config/deps/lib/python3.6/site-packages/locationsharinglib/locationsharinglib.py", line 292, in get_shared_people people = [Person(info) for info in output[0]] TypeError: 'NoneType' object is not iterable`

B is an older account, C was created today.

Something wierd tho : on https://myaccount.google.com/device-activity page i cannot see the script accessing my C account.

**Comment by costastf** [comment]
Could you please try the library on its own using the usage documentation and report back with a debug output?

**Comment by pixeye33** [comment]
Well that is weird : 
i've just tried with C account, no output
tried with B account to know what the ouput should look like : works
got to my phone gmap on A account and sees that the shares were **all** disabled (not by me), i re-enable them
then again with C : It works now !

Restarted Home assistant without touchin anything (was still using C account) : Works OK now.

Glad it's working fine now, but i guess the issue was on Google side as my shares were all magically disabled and still could track via B account...

Thanks for your amazing work :)

**Comment by lvlie** [comment]
I think this might be reopened; this issue seems to arise when a person who is sharing location with you is "offline" in google maps. This seems to happen when an update is not sent for some time, for example with my wife's iPhone. When I open up google maps on her phone and update the location, I can see the updated location in the 3rd account again (use in HA) and the error goes away. 

I cannot see any other issue or pull request referencing this and its not a big problem (offline means no updated location anyway), its just the error message in the log

**Comment by lvlie** [comment]
Updated to the latest version on pypi; issue still persists. It seems the data for longitude, latitude and last update time are set to none, which causes the error. I think I might have fixed this on the iPhone by settings "update on background" to true in settings for google maps (which sets the phone offline when maps isnt opened for some time); it might be prettier to catch the error :)

**Comment by costastf** [comment]
On the latest version I have turned this into a debug error from am exception one so you should not be getting it any more.could you please provide me with an output of what you are getting so I can understand the problem?

**Comment by lvlie** [comment]
Apologies, after enabling background updates for maps on the iphone the error went away after a restart of HA and I did not save the log.... 😵 
Was using 1.2.1 after "pip install --upgrade locationsharinglib" which still threw the error in the log, but I see yesterdays commits might indeed fix the error. 

The issue remains that HA would still report the last known location, while "offline" in google maps should probably translate into an "unknown" location for HA. But that might be something for the component in HA to actually handle...

**Comment by costastf** [comment]
No worries :) closing this.
