### ISSUE TITLE
connecting with 2-step verification

### ISSUE THREAD

**Issue by chelming** [costastf/locationsharinglib#14]
is there a way to connect using an account that has 2-step verification turned on? I tried using an [App password](https://support.google.com/accounts/answer/185833?hl=en) but it told me invalid credentials.

**Comment by costastf** [comment]
please try https://github.com/costastf/locationsharinglib/tree/f-authenticate-interactively, running the cli.py on the root and let me know how it works for you.

**Comment by chelming** [comment]
I get a cookies file generated but there's no step asking me to either verify my device or enter my second factor.

**Comment by costastf** [comment]
That probably means that there are more ways than one that google does 2FA probably changing on location. The 2FA was a contribution that worked for the person that wrote it and it was validated that it worked with the current code, but apparently there are other cases out there.

**Comment by chelming** [comment]
The first thing I can see is that `_handle_prompt` gets called if `challenge/az` is in the response url, but I'm seeing `challenge/sk` instead. I'm not sure what the az or sk means (if I were to guess I'd say that sk is software key but that's just a wild guess). When I hit challenge/sk in a non-U2F compatible browser, I get the option to "try another way", get sent to `challenge/selection` where I can then pick "tap yes on your phone or tablet" where I get redirected to a `challenge/az` page.

I'll see if I can figure out how that challenge/az url is crafted and if I can get to it without having to go through the steps of clicking "try another way" and then "tape yes from your phone or tablet".

It might be worth seeing if there's a way to get Google Authenticator codes working, but for now I think most people would be ok with turning on the "tap yes" method for two-step verification.

**Comment by chelming** [comment]
Well I think I got it working. I just need to make it more _pythonic_.

```python
    def _authenticate(self):
        initial_form = self._initialize()
        password_form = self._submit_email(initial_form)
        response = self._submit_password(password_form)
        if 'challenge/az' in response.url:
            self._handle_prompt(response)
        elif 'challenge/' in response.url:
            # look for the "skip" section
            soup = Bfs(response.text, 'html.parser')
            all_forms = soup.findAll('form')
            for form in all_forms:
                if '/signin/challenge/skip' in form.get('action'):
                    form = form
            payload = self._get_hidden_form_fields(form)
            url = '{login_url}{form_action}'.format(
                    login_url=self._login_url,
                    form_action=form.get('action')
                )
            response = self._session.post(url, data=payload)
            # look for the "az" auth type
            soup = Bfs(response.text, 'html.parser')
            all_forms = soup.findAll('form')
            for form in all_forms:
                if '/signin/challenge/az' in form.get('action'):
                    form = form
            url = '{login_url}{form_action}'.format(
                    login_url=self._login_url,
                    form_action=form.get('action')
                )
            payload = self._get_hidden_form_fields(form)
            response = self._session.post(url, data=payload)
            self._handle_prompt(response)
```

Any tips for this? Should it all be moved to `_handle_prompt`?

fwiw, the only thing new is that the `elif` has been added

**Comment by chelming** [comment]
The whole, looking for the form, getting the action from the form, posting the form part seems repetitive. At the very least, should I add a new function for looking for and going to the "challenge/skip" page then looking for and going to the "click yes/az' method?
```python
            soup = Bfs(response.text, 'html.parser')
            all_forms = soup.findAll('form')
            for form in all_forms:
                if '/signin/challenge/skip' in form.get('action'):
                    form = form
            payload = self._get_hidden_form_fields(form)
            url = '{login_url}{form_action}'.format(
                    login_url=self._login_url,
                    form_action=form.get('action')
                )
            response = self._session.post(url, data=payload)
``` 

Really, the only difference is looking for form action '/signin/challenge/skip', and then repeating the process for '/signin/challenge/az'.

**Comment by chelming** [comment]
They apparently do rate limiting too...
```html
<form action="javascript:return false;" data-unavailable="4">
    <button disabled="" type="submit">
        <img src="//ssl.gstatic.com/accounts/marc/authzen.png"/>
        <span class="mSMaIe">
            <span class="NCPpXe">Tap <strong>Yes</strong> on your phone or tablet</span>
            <em class="YtZ0Vb" jsname=TMYUoe">Too many Google prompts already sent</em>
        </span>
    </button>
</form>
```

**Comment by chelming** [comment]
So, I got this somewhat working in the sense that my cookies are valid. My current issue is that `service.get_authenticated_person()` and `service.get_all_people()` come up empty.

Any ideas on how to troubleshoot that?

I'm not sure how to decipher `service._get_data()` but it's definitely missing locations and doesn't match what I see in google maps.

**Comment by chelming** [comment]
And now I'm hitting a captcha 😩

**Comment by costastf** [comment]
I will look into this and clean up the code this afternoon, thanks, you are doing an awesome job!

**Comment by costastf** [comment]
I have been too busy to help with this, sorry. What is the current status? What can I help with?

**Comment by jo45** [comment]
I'm looking for this too. I tryed your code cwhits but without success.

**Comment by chelming** [comment]
@jo45 how far did you get? what part aren't you having success with? what 2FA types do you have enabled for you account?

**Comment by jo45** [comment]
@cwhits I don't have any error. It print nothing, and the exit code is 0.
It does not ask me for anything. I enabled TOTP (aka Google Authenticator), in order to be able to generate OTP from shell.

**Comment by chelming** [comment]
You need to also enable the "tap yes" Google prompt method, since that's what this uses.

**Comment by jo45** [comment]
Actually, it's just one possibility. Once your activate 2FA, you can change types of 2FA (TOTP, phone prompt, USB token, SMS, phone call and of course emergency codes). I tried with phone prompt, had the invite on my phone, but script immediatly ends. I pressed "yes" on phone, restart script, and have the same result again and again. I tried with TOTP (it is my goal because it is fully scriptable so I could use locationsharinglib from crontab), but script does not ask for anything and exit with code 0.

**Comment by chelming** [comment]
what script are you using? you should only need to run the cli.py script once to have it generate the .google_maps_location_sharing.cookies file. After that you'd use the rest of the code normally.

**Comment by jo45** [comment]
I run this:

```
username = "xxx"
password = "xxx"
from locationsharinglib import Service
service = Service(username, password)
for person in service.get_all_people():
    print(person)
```

Will try cli.py tonight. Thank you.

**Comment by chelming** [comment]
run cli.py with your email and password, then go and run the code you just posted. you can also try `service._get_data()` to see that you're getting a response. 

I'm able to connect but I'm not getting back the correct data from google. It's empty and doesn't match what I see going through the website.

**Comment by jo45** [comment]
Nothing happen when I try to run cli.py. Exit with code 0, print nothing. I can't find the cookie. Where is it stored?

**Comment by costastf** [comment]
I have released v2 of the library with the 2FA additions and the cli helper. Usage can be found http://locationsharinglib.readthedocs.io/en/latest/usage.html.

**Comment by ghost** [comment]
I found marc zebauth as one of the users of my account. As well i have 6  clones of my samsung in google prompt list. Plus devices i lost :(

**Comment by ghost** [comment]
I found marc zenauth as one of the users of my account. As well i have 6  clones of my samsung in google prompt list. Plus devices i lost :(

**Comment by ghost** [comment]
As well laptop is destroyd and i really do not know is really possible to fix something. I use local modified  net my apps all leaks everything is preconfigured.
