### ISSUE TITLE
Unable to dump cookies

### ISSUE THREAD

**Issue by michaelarnauts** [costastf/locationsharinglib#2]
The code to dump the cookies is not working since the file descriptor is not opened in `binary` mode.

```py
from locationsharinglib import Service

service = Service('xxxxxx@gmail.com', 'xxxxx')
service.export_session('samples')
```

Throws the following error:
```
Traceback (most recent call last):
  File "samples/test.py", line 5, in <module>
    service.export_session('samples')
  File "/home/michael/Development/locationsharinglib/locationsharinglib/locationsharinglib.py", line 211, in export_session
    pickle.dump(self._session.cookies, cookie_file)
TypeError: write() argument must be str, not bytes
```

This can be fixed by opening the `cookies.pickle` file as `wb` instead of just `w`.

```py
    def export_session(self, path):
        """Exports the session's cookies to the provided path

        Args:
            path: The path to save the cookies.pickle file

        Returns:
            True on success.

        """
        cfile = os.path.join(path, 'cookies.pickle')
        with open(cfile, 'wb') as cookie_file: # <- this line
            pickle.dump(self._session.cookies, cookie_file)
            return True
```

**Comment by costastf** [comment]
I wrote this on 2.7 so this is an issue with 3 and bytes of course. Would you like to make an MR and add your name to the contributors or would you prefer for me to just fix this?

**Comment by michaelarnauts** [comment]
The reading of the cookie should also be binary, I will create a MR for these changes.

I do seem to have an issue that my cookie file is invalid, not sure if this is related.
```
locationsharinglib.locationsharinglibexceptions.InvalidCookies: The cookies provided do not provide a valid session.Please authenticate normally and save a valid session again
```

EDIT: Okay, this is unrelated. It seems google blocked access to my account since it was "suspicious", I approved the login and all was fine again.

**Comment by costastf** [comment]
i guess that it is. Your MR will be more than welcome :)

**Comment by costastf** [comment]
I am guessing that you tested it and it works with the binary mode?

**Comment by michaelarnauts** [comment]
Yep, it does.

**Comment by costastf** [comment]
Hi @michaelarnauts are you by any chance doing anything on the HA device_tracker front with this?

**Comment by michaelarnauts** [comment]
Not yet, but I guess that's the purpose of this library. I've made a device tracker component in the past (Aruba), and it's not that hard, I just haven't had the time to look into it.
