### ISSUE TITLE
Could not load people

### ISSUE THREAD

**Issue by kapiorr** [costastf/locationsharinglib#26]
Home assistant installed in a virtual environment 0.70.1, python 3.5.3, debian 9.4

`2018-06-03 23:36:29 DEBUG (Thread-13) [locationsharinglib.Service] Could not load people, response:`

**Comment by jantman** [comment]
I'm having the same issue. If I run locationsharinglib directly but the same way that homeassistant does, the output includes:

```
DEBUG:locationsharinglib.Service:Could not load people, response: [None, None, 'STRING', 'STRING', None, None, 'BASE64', 1800, 1529942047748, None, None, [0]]
```

Where each ``STRING`` is a string that appears to match A-Za-z0-9_ and BASE64 is a string that appears to be base64-encoded.

**Comment by jedi7** [comment]
guys, see my pull request :)

**Comment by roblandry** [comment]
confirmed @jedi7 PR fixed my issue.

**Comment by kapiorr** [comment]
works fine
