### ISSUE TITLE
get-maps-cookies fails

### ISSUE THREAD

**Issue by jezzaaa** [costastf/locationsharinglib#27]
I have 2FA setup on my a/c. When trying to create a cookie, I get this:

  File "/home/jpl/.virtualenvs/locationsharinglib/local/lib/python2.7/site-packages/locationsharinglib/locationsharinglib.py", line 334, in _handle_prompt
    data_key = soup.find('div', {'data-api-key': True}).get('data-api-key')

My phone pops up a message asking if it was me, so that's nice. But still the error, and no cookie.

Memory not so good, but I /think/ the first attempt had my phone pop up a prompt asking me to choose between three two-digit numbers, which I cancelled. Since then, the above error, no numbers to choose, and just the "was this you?" prompt.

**Comment by mdwilst** [comment]
same here, disabled 2FA and working fine. Enabled 2FA again, getting a push on my mobile to confirm the login, but before being able to confirm, script terminating with an  error of:

    data_key = soup.find('div', {'data-api-key': True}).get('data-api-key')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by costastf** [comment]
Please use v2.0.10 and report back. I am handling the exception and properly logging so we can try to find out what happens. Apparently there are multiple 2FA methods for google propably geo dependent. What fun....

**Comment by jezzaaa** [comment]
Thanks. I upgraded to 2.0.11, and now I can make a cookies file, yay!

However the file doesn't seem to parse when I run the example code on the Usage web page:
```
$ python ./test.py
Traceback (most recent call last):
  File "./test.py", line 6, in <module>
    service = Service(username, password, cookies_file="YOUR_COOKIES_FILE")
  File "/home/jpl/.virtualenvs/locationsharinglib/local/lib/python2.7/site-packages/locationsharinglib/locationsharinglib.py", line 370, in __init__
    cookies_file=cookies_file)
  File "/home/jpl/.virtualenvs/locationsharinglib/local/lib/python2.7/site-packages/locationsharinglib/locationsharinglib.py", line 194, in __init__
    if cookies_file and self._validate_cookie(cookies_file):
  File "/home/jpl/.virtualenvs/locationsharinglib/local/lib/python2.7/site-packages/locationsharinglib/locationsharinglib.py", line 221, in _validate_cookie
    raise InvalidCookies(message)
locationsharinglib.locationsharinglibexceptions.InvalidCookies: The cookies provided do not provide a valid session.Please authenticate normally and save a valid session again
```
Looking at the code where the error was raised, it looks to be searching for "Sign in - Google Accounts". If I capture "response.text" I can see <title>Sign in - Google Accounts</title> in the response. I don't know enough Python to get any further.

**Comment by jezzaaa** [comment]
Duh, I obviously don't know enough Python to follow the code correctly. I now realise that the presence of the "Sign in" message means that the authentication failed. But I don't know why. I've re-created the cookie file, and it still doesn't work.

**Comment by jezzaaa** [comment]
Whoops, I was wrong. If I delete the cookie file, and recreate it, the test program runs the first time without any errors (or output). The second time, it fails with the error as shown above.

I put a password in the test program, but I wondered, isn't the cookie file sufficient?

**Comment by mdwilst** [comment]
getting an "Unexpected response received" error. On the page retrieved (which is the 2FA login confirmation), nothing like data-api-key or data-tx-id.
![unbenannt](https://user-images.githubusercontent.com/10384869/42413046-ed0b03c0-8218-11e8-90a5-c666a7ef2e20.jpg)

**Comment by costastf** [comment]
Could you please paste the unexpected response you got paying attention not
to post any personal details? The unexpected response message was on
purpose to get exactly this output.

**Comment by mdwilst** [comment]
quite difficult to see what is personal there - there are some lengthy strings in there which I assume are tokens?

Ignoring all the JavaScript, basically returns

//# sourceURL=/accounts/static/_/js/k=gaia.gaiafe_glif.de.AgsyvCnpg3Y.O/am=xxxx/rt=j/d=1/rs=yyyy/m=glifb,identifier,unknownerror</script><script nonce="zzzz">var AF_initDataKeys = []
; var AF_dataServiceRequests = {}; var AF_initDataChunkQueue = []; var AF_initDataCallback; var AF_initDataInitializeCallback; if (AF_initDataInitializeCallback) {AF_initDataInitializeCallback(AF_initDataKeys, AF_initDataChunkQueue, AF_dataServiceRequests);}if (!AF_initDataCallback) {AF_initDataCallback = function(chunk) {AF_initDataChunkQueue.push(chunk);};}</script></head><body id="yDmH0d" class="nyoS7c SoDlKd" jscontroller="Uas9Hd" jsaction="rcuQ6b:npT2md;click:FAbpgf"><div class="uc81Ff wKBl8c bbRbR"><div class="LJtPoc v7usYb" id="initialView" role="presentation" jsname="WsjYwc" jscontroller="g3tFzd" jsaction="rcuQ6b:wVXPKc,eyofDf;CfTBWd:r0xNSb;enEq8c:Yd2OHe;Z2AmMb:nnGvjf;eqoCse:oUMEzf;RdYeUb:oUMEzf;EJh3N:vYWWBd;"><div class="RZBuIb c8DD0" aria-hidden="true"><div jscontroller="ltDFwf" jsaction="transitionend:Zdx3Re" jsname="Igk6W" role="progressbar" class="sZwd7c B6Vhqe qdulke jK7moc"><div class="xcNBHc um3FLe"></div><div jsname="cQwEuf" class="w2zcLc Iq5ZMc"></div><div class="MyvhI TKVRUb" jsname="P1ekSe"><span class="l3q5xe SQxu9c"></span></div><div class="MyvhI sUoeld"><span class="l3q5xe SQxu9c"></span></div></div></div><div class="bdf4dc" jsname="f2d3ae" role="presentation"><div class="slptg"><div class="fctIrd" jsname="n7vHCb" jscontroller="UXmCpc" jsaction="rcuQ6b:qg4Ic;ZMcYSd:WPi0i;" data-can-enhance="false" data-oauth-third-party-logo-url="" data-init-branding="jcJzye" aria-hidden="true"><div jsname="jjf7Ff" jscontroller="P9M9H" jsaction="rcuQ6b:npT2md"><div id="logo" class="SSBsw" title="Google"><div class="qZp31e" jsname="l4eHX"><svg viewBox="0 0 74 37" width="74" height="37" preserveAspectRatio="xMinYMin" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><g id="qaEJec"><path fill="#ea4335" d="M67.954 16.303c-1.33 0-2.278-.608-2.886-1.804l7.967-3.3-.27-.68c-.495-1.33-2.008-3.79-5.102-3.79-3.068 0-5.622 2.41-5.622 5.96 0 3.34 2.53 5.96 5.92 5.96 2.73 0 4.31-1.67 4.97-2.64l-2.03-1.35c-.673.98-1.6 1.64-2.93 1.64zm-.203-7.27c1.04 0 1.92.52 2.21 1.264l-5.32 2.21c-.06-2.3 1.79-3.474 3.12-3.474z"/></g><g id="YGlOvc"><path fill="#34a853" d="M58.193.67h2.564v17.44h-2.564z"/></g><g id="BWfIk"><path fill="#4285f4" d="M54.152 8.066h-.088c-.588-.697-1.716-1.33-3.136-1.33-2.98 0-5.71 2.614-5.71 5.98 0 3.338 2.73 5.933 5.71 5.933 1.42 0 2.548-.64 3.136-1.36h.088v.86c0 2.28-1.217 3.5-3.183 3.5-1.61 0-2.6-1.15-3-2.12l-2.28.94c.65 1.58 2.39 3.52 5.28 3.52 3.06 0 5.66-1.807 5.66-6.206V7.21h-2.48v.858zm-3.006 8.237c-1.804 0-3.318-1.513-3.318-3.588 0-2.1 1.514-3.635 3.318-3.635 1.784 0 3.183 1.534 3.183 3.635 0 2.075-1.4 3.588-3.19 3.588z"/></g><g id="e6m3fd"><path fill="#fbbc05" d="M38.17 6.735c-3.28 0-5.953 2.506-5.953 5.96 0 3.432 2.673 5.96 5.954 5.96 3.29 0 5.96-2.528 5.96-5.96 0-3.46-2.67-5.96-5.95-5.96zm0 9.568c-1.798 0-3.348-1.487-3.348-3.61 0-2.14 1.55-3.608 3.35-3.608s3.348 1.467 3.348 3.61c0 2.116-1.55 3.608-3.35 3.608z"/></g><g id="vbkDmc"><path fill="#ea4335" d="M25.17 6.71c-3.28 0-5.954 2.505-5.954 5.958 0 3.433 2.673 5.96 5.954 5.96 3.282 0 5.955-2.527 5.955-5.96 0-3.453-2.673-5.96-5.955-5.96zm0 9.567c-1.8 0-3.35-1.487-3.35-3.61 0-2.14 1.55-3.608 3.35-3.608s3.35 1.46 3.35 3.6c0 2.12-1.55 3.61-3.35 3.61z"/></g><g id="idEJde"><path fill="#4285f4" d="M14.11 14.182c.722-.723 1.205-1.78 1.387-3.334H9.423V8.373h8.518c.09.452.16 1.07.16 1.664 0 1.903-.52 4.26-2.19 5.934-1.63 1.7-3.71 2.61-6.48 2.61-5.12 0-9.42-4.17-9.42-9.29C0 4.17 4.31 0 9.43 0c2.83 0 4.843 1.108 6.362 2.56L14 4.347c-1.087-1.02-2.56-1.81-4.577-1.81-3.74 0-6.662 3.01-6.662 6.75s2.93 6.75 6.67 6.75c2.43 0 3.81-.972 4.69-1.856z"/></g></svg></div></div></div></div><div id="view_container" class="JhUD8d SQNfcc" jscontroller="WFS13" jsaction="rcuQ6b:npT2md" jsmodel="Z7PiFb qFmk3b qbZ0Se nqpTHe YPPRX eV9nn Xu2csd hc6Ubd" data-app-config="%.@.[null,null,null,null,&quot;default&quot;,null,null,null,null,null,[]
,null,null,null,null,null,null,null,&quot;https://accounts.google.com/SignUp?continue\u003dhttps%3A%2F%2Faccounts.google.com%2FManageAccount&quot;,null,null,[]
,[null,&quot;https://business.google.com/add/info?service\u003dgaia&quot;]
]
,null,null,null,null,null,null,&quot;signin/v2/challenge/az&quot;,null,null,null,null,&quot;https://accounts.google.com/ManageAccount&quot;,null,[2,1,null,1,&quot;https://accounts.google.com/ServiceLogin?checkedDomains\u003dyoutube\u0026pstMsg\u003d0\u0026TL\u003dzzzz\u0026flowName\u003dGlifWebSignIn\u0026cid\u003d4&quot;,null,[]
,4,[]
,&quot;GlifWebSignIn&quot;]
,true,[null,null,[]
]
,1,null,null,null,null,null,null,null,null,null,null,null,null,false,null,false,true,[[[&quot;checkedDomains&quot;,&quot;youtube&quot;]
,[&quot;pstMsg&quot;,&quot;0&quot;]
,[&quot;TL&quot;,&quot;zzzz&quot;]
,[&quot;flowName&quot;,&quot;GlifWebSignIn&quot;]
]
] 

(continues like this)

Happy to share responding to robii@gmx.net

**Comment by kenthua** [comment]
Appears I'm getting this page rendered where it errors out.  

```
ERROR:locationsharinglib.CookieGetter:Could not open pickle file, either file does not exist or no read access.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): accounts.google.com:443
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "GET /ServiceLogin HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "POST /signin/v1/lookup HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "POST /signin/challenge/sl/password HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "GET /signin/v2/challenge/totp?checkedDomains=youtube&pstMsg=0&TL=AHnYQ...kg&flowName=GlifWebSignIn&cid=2 HTTP/1.1" 200 None
DEBUG:locationsharinglib.CookieGetter:Response : <!doctype html><html lang="en" dir="ltr"><head><base href="https://accounts.google.com/">
...
_.KK.prototype.WD=function(a){return"USERNAME_RECOVERY"==a.getContext()?30==_.Ii(a)?"signin/v2/usernamerecovery/challenge/ipe":"signin/v2/usernamerecovery/challenge/ipp":30==_.Ii(a)?"signin/v2/challenge/ipe":"signin/v2/challenge/ipp"};
```

![image](https://user-images.githubusercontent.com/8052337/42488969-35a56486-83bd-11e8-8975-a2e465960429.png)

**Comment by pnbruckner** [comment]
I'm getting similar results. I installed locationsharinglib on a completely different machine than HA in a python3 venv. I ran get-maps-cookies and it spit out what looks like an html page to stderr. I captured that and it looks just like in the previous post. When get-maps-cookies was run my phone asked if it was me logging in, to which I clicked yes. But no cookies file.

**Comment by costastf** [comment]
Hi all, it seems that there are multiple challenges responses and multiple api versions. I am currently on vacation and will be back after the 24th. I will refactor the library to have more extensive debugging so we can identify all those differences and cover them. Please be patient until then.

**Comment by costastf** [comment]
For the situation mentioned here, it seems that there is no option to use a push notification as a 2fa but only to enter a code from Google authenticator. That situation will probably not be handled correctly in any case since the process cannot be interactive. I would look into the security options of the account for a push notification option.

**Comment by costastf** [comment]
Please have a look at https://support.google.com/accounts/answer/7026266?co=GENIE.Platform%3DiOS&hl=en

**Comment by roblandry** [comment]
Just a little digging into this issue, these are the things i am seeing...

First, home assistant has several python packages requiring other versions. Maybe inconsequential, but none the less, im listing them.
```
upsmychoice 1.0.6 has requirement beautifulsoup4==4.5.1, but you'll have beautifulsoup4 4.6.0 which is incompatible.
upsmychoice 1.0.6 has requirement python-dateutil==2.6.0, but you'll have python-dateutil 2.7.3 which is incompatible.
upsmychoice 1.0.6 has requirement requests==2.12.4, but you'll have requests 2.19.1 which is incompatible.
myusps 1.3.2 has requirement python-dateutil==2.6.0, but you'll have python-dateutil 2.7.3 which is incompatible.
myusps 1.3.2 has requirement requests==2.12.4, but you'll have requests 2.19.1 which is incompatible.
myusps 1.3.2 has requirement selenium==2.53.6, but you'll have selenium 3.14.0 which is incompatible.
motorparts 1.0.2 has requirement beautifulsoup4==4.5.1, but you'll have beautifulsoup4 4.6.0 which is incompatible.
motorparts 1.0.2 has requirement requests==2.12.4, but you'll have requests 2.19.1 which is incompatible.
geizhals 0.0.7 has requirement beautifulsoup4>=4.6.3, but you'll have beautifulsoup4 4.6.0 which is incompatible.
fedexdeliverymanager 1.0.6 has requirement beautifulsoup4==4.5.1, but you'll have beautifulsoup4 4.6.0 which is incompatible.
fedexdeliverymanager 1.0.6 has requirement python-dateutil==2.6.0, but you'll have python-dateutil 2.7.3 which is incompatible.
```
Secondly, i am unable to get past the cookie file creation.  The results i am seeing is it is requiring a captcha. (I dumped the response.text to a file and opened in a browser)
```
Traceback (most recent call last):
  File "/usr/local/bin/get-maps-cookies", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/locationsharinglib/cli.py", line 83, in main
    CookieGetter(args.email, args.password, args.cookies_file)
  File "/usr/local/lib/python3.6/site-packages/locationsharinglib/locationsharinglib.py", line 315, in __init__
    cookies_file=cookies_file)
  File "/usr/local/lib/python3.6/site-packages/locationsharinglib/locationsharinglib.py", line 198, in __init__
    self._authenticate()
  File "/usr/local/lib/python3.6/site-packages/locationsharinglib/locationsharinglib.py", line 324, in _authenticate
    selection_form = self._skip_challenge(response)
  File "/usr/local/lib/python3.6/site-packages/locationsharinglib/locationsharinglib.py", line 283, in _skip_challenge
    form = self._get_required_form(response, '/signin/challenge/skip')
  File "/usr/local/lib/python3.6/site-packages/locationsharinglib/locationsharinglib.py", line 272, in _get_required_form
    raise NoExpectedFormOption
locationsharinglib.locationsharinglibexceptions.NoExpectedFormOption
```
Digging in, i see that https://github.com/costastf/locationsharinglib/blob/b518c89bc37dbec113c94f6fb80c86b0fe7d300a/locationsharinglib/locationsharinglib.py#L246
uses v1, when changing to v2 a cookie is created.

Lastly, using the hack for v2, the cookie is not working in the session to login.
```
Traceback (most recent call last):cationsharinglib.py /usr/local/lib/python3.6/si
  File "/usr/local/bin/get-maps-cookies", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/locationsharinglib/cli.py", line 83, in main
    CookieGetter(args.email, args.password, args.cookies_file)
  File "/usr/local/lib/python3.6/site-packages/locationsharinglib/locationsharinglib.py", line 329, in __init__
    cookies_file=cookies_file)
  File "/usr/local/lib/python3.6/site-packages/locationsharinglib/locationsharinglib.py", line 194, in __init__
    if cookies_file and self._validate_cookie(cookies_file):
  File "/usr/local/lib/python3.6/site-packages/locationsharinglib/locationsharinglib.py", line 227, in _validate_cookie
    raise InvalidCookies(message)
locationsharinglib.locationsharinglibexceptions.InvalidCookies: The cookies provided do not provide a valid session.Please authenticate normally and save a valid session again
```
Additionally i have gone from using a username/password to 2FA using an app password.
I hope this information is helpful as i very much enjoy using this package in home assistant, however it hasn't seemed to be working in a bit. Thanks Google. :-)

**Comment by costastf** [comment]
@roblandry thanks for the digging in. I don't think that changing the api version provides any benefit and it is likely that the cookie file created is just a dump of garbage since the response of that api version is unknown. The problem with all this is that there are multiple api versions and differences in the way google responds according to location I think. I will try to add better logging capabilities in the library so all differences can be intentified an accounted for in the long run.

**Comment by costastf** [comment]
Closing this as it has been stale for some time now.
