### ISSUE TITLE
Home asistant 0.73

### ISSUE THREAD

**Issue by migromao** [costastf/locationsharinglib#28]
Hi , latest version of HA is not compatible having a requirement issue with your library

locationsharinglib 2.0.7 has requirement requests==2.18.4, but you'll have requests 2.19.1 which is incompatible.

could this be looked ?

**Comment by costastf** [comment]
v2.0.9 bumped dependency to the compatible one.

**Comment by migromao** [comment]
How should I proceed as it won't let me via hassbian script

**Comment by costastf** [comment]
Sorry, I don't understand the question

**Comment by migromao** [comment]
HI,
the error on lib was resolved with an workaround

`curl -sSL https://gitlab.com/ludeeus/toolbox/raw/master/homeassistant/workarounds/0.73.0%20-%20sensor.dht-hassbian.sh | sudo bash`

how should i resolve for good ?

**Comment by costastf** [comment]
Again, i am sorry but I do not understand the question. You can update the
component to reference the latest version of the library if that is what
you are asking.

**Comment by migromao** [comment]
probably that's what i'm looking for .. but i always use the hassbian-config script for upgrading my HA
how should i do it for just the lib or component ?

**Comment by costastf** [comment]
you need to locate the component path in your installation and update the
version in the requirement file.

so you would update


REQUIREMENTS = ['locationsharinglib==2.0.7']

with

REQUIREMENTS = ['locationsharinglib==2.0.11']

and restart your HA instance

**Comment by migromao** [comment]
thank you -- will try
