### ISSUE TITLE
Including phone battery charge % to populate along with location data which get shared.

### ISSUE THREAD

**Issue by hitesh-singh** [costastf/locationsharinglib#31]
Suggestion:

From past few days I could see in the google maps "Location sharing" page there is a indication of person's current phone battery charge % and charging status as well, beside how far the person is from you.

If possible could any one please include the same as well so that i can fetch the same information in Home assistant.

Nope: I'm not a developer and i don't know what to do in order to achieve this, this was just a suggestion. Would love to hear any update on this from any one.

**Comment by hitesh-singh** [comment]
![img-20180809-wa0004](https://user-images.githubusercontent.com/16590121/43897544-007e9dc2-9bfa-11e8-91d2-5e3ddc5e39cb.jpg)

**Comment by digiblur** [comment]
Noticed that myself the other day and was going to dig through the code to see if it was exposed on the call.

**Comment by kabili207** [comment]
I mentioned this in issue #30, but the data structure used by the website doesn't contain the battery information. Until this is exposed on the **web** version of Google Maps, this feature can't be added.

**Comment by costastf** [comment]
Thank you Amy!

**Comment by kabili207** [comment]
Looks like Google just added battery levels to the web version. Seems to be stored in `data[13][1]`.

Edit: and it looks like `data[13][0]` is a bit value indicating if the phone is plugged in or not.
