### ISSUE TITLE
Can't Get Google Tracker to Work

### ISSUE THREAD

**Issue by TexanScot** [costastf/locationsharinglib#33]
Been spending a little time trying to configure the Google Tracker platform without much success.

The only reference that I see within the logs is:

```
[homeassistant.loader] Loaded device_tracker.google_maps from homeassistant.components.device_tracker.google_maps
[homeassistant.components.device_tracker] Setting up device_tracker.google_maps
```
The .google_maps_location_sharing.cookies is created in the HA config folder and a coupe of times I received messages on my phone asking if I was trying to login from another computer. However I do not see any API requests on my google account which would lead me to believe that HA is not being successful in trying to login to the dummy account that my phone is sharing my location with.

When I login to the dummy account I don't see anything under 'Device Activity' apart from the manual login that I did before trying to get this running.

Not quite sure where I go from here!

**Comment by costastf** [comment]
Pease try the library independently from HA as detailed in it's documentation and report any issues.

**Comment by costastf** [comment]
Closing this as there is no extra info.
