### ISSUE TITLE
Release pinning

### ISSUE THREAD

**Issue by fabaff** [costastf/locationsharinglib#38]
Please remove the pinning in `requirements.txt` or make it less strict. E.g.,  

```text
beautifulsoup4==4.6.0
```

Original issue: https://github.com/home-assistant/home-assistant/issues/16947

**Comment by costastf** [comment]
v3.0.1 fixes this.

**Comment by costastf** [comment]
v3.0.2 fixes https://github.com/home-assistant/home-assistant/issues/15076 also.

**Comment by fabaff** [comment]
Thanks
