### ISSUE TITLE
Cli pipe

### ISSUE THREAD

**Issue by Enelar** [costastf/locationsharinglib#46]
Trying to setup reporting location every few minutes as docker serverless image. Is there any chance to achieve that without python?

**Comment by costastf** [comment]
Not sure what you mean. This is written in python so no, not really. If you mean without having python installed in your docker image, then you could use pyinstaller to make a binary of this library along with some custom code that would use this on an infinite loop.

**Comment by costastf** [comment]
Closing this as this is not really an issue with the code.
