### ISSUE TITLE
Can you create a new tag for example 3.0.10

### ISSUE THREAD

**Issue by rolfberkenbosch** [costastf/locationsharinglib#55]
Hi, I saw that you have updated the code. I want to push the new code to my home assistant. The current version with the old code is 3.0.9. Can you create a new tag for example 3.0.10 ?
Thanks in advance!

**Comment by costastf** [comment]
The latest tag with the patch from lufton has been updated some days now,
is in version 3.0.11 and its available in
https://pypi.org/project/locationsharinglib/ as a normal python package.
