### ISSUE TITLE
Improve reliability

### ISSUE THREAD

**Issue by michaelarnauts** [costastf/locationsharinglib#6]
Google keeps on marking the logins as suspicious, I guess due to missing useragents or other things.
After a few tries, it asks additional details before the login succeeds.

**Comment by michaelarnauts** [comment]
I've tried to pass a user-agent also, but it seems to need more then that.

This might be usefull also: https://github.com/tubaman/google-login

**Comment by costastf** [comment]
I am afraid that this has nothing to do with the code. This is basic google security and you will get the exact same thing if you try to login with any browser. This is not something that can be worked around. The only thing that can be done is from the google accounts side to turn off all security measures. Closing this as this not fixable.

**Comment by costastf** [comment]
By the way, amazing job with the HA component. Thanks!

**Comment by michaelarnauts** [comment]
Hmm, I don't agree. Since the useragent is missing, google is marking the account login as suspicious. There are a few ways to make it less obvious that we are a script.

The Windows and linux login are from the browser, the middle one is from python without a useragent.

See here:
![image](https://user-images.githubusercontent.com/1193779/36301213-56a53320-1304-11e8-99ba-4184ca3d4d89.png)

**Comment by michaelarnauts** [comment]
I'm afraid if this issue can't be adressed, the hass device_tracker will never work reliably.

**Comment by costastf** [comment]
Adding a user agent will just make the device known but will not make security any less strict i am afraid. Google is pretty good at securing their stuff.

**Comment by costastf** [comment]
What I did was I run the library part to login from my laptop while being logged in the account so the location and the hardware matched and then moved the cookies export to my HA and it just works fine like this. On the account it actually appears as my laptop being connected twice. Maybe we could specify this manual step as a way to initially get the appropriate cookies on the documentation. Keep in mind that we are trying to imitate valid usage, and of course that is exactly what google is trying to avoid and they are really good at what they do.

**Comment by costastf** [comment]
It still beats the way the previous component needed to be set up to work ;)
