### ISSUE TITLE
Unable to get it working

### ISSUE THREAD

**Issue by au190** [costastf/locationsharinglib#61]
Iam using Python 3.6 ev
Trying to run to get the location without success.
Can you advice ? Is this example working with py ?

Also I try to use from d:\Temp\Internet\a\locationsharinglib-master\setup_aliases.ps1 - still no response nothing happend .
How can I check this lib ? How can I run this ps1 script ?
Can you paste an example ?

Thx R.

**Comment by costastf** [comment]
Please check out documentation at https://locationsharinglib.readthedocs.io/en/latest/

**Comment by NorthernMunkey** [comment]
excellent work, from what i am reading elsewhere, Hassio integration is broken, and your workarounds aren't working anymore is this the case still?

**Comment by au190** [comment]
I can rum it from python, but Ian using older release. Its working perfectly. 

One question, the battery level not allways show, but sometimes I can see, why ?

**Comment by costastf** [comment]
Maybe the response does not always send it? @NorthernMunkey I do not understand the question. Hassio uses an old version of the library that tries to do the authentication and works for some people depending on where they are in the world and what google authenticates them with. On the latest version of the library I have removed the authentication code completely and expect a working cookie file to be provided which you can obtain by using https://github.com/costastf/mapscookiegettercli/blob/master/USAGE.rst .

**Comment by NorthernMunkey** [comment]
Error setting up platform legacy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/setup.py", line 76, in async_setup_legacy
    tracker.see, discovery_info)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/google_maps/device_tracker.py", line 39, in setup_scanner
    scanner = GoogleMapsScanner(hass, config, see)
  File "/usr/src/homeassistant/homeassistant/components/google_maps/device_tracker.py", line 60, in __init__
    self._update_info()
  File "/usr/src/homeassistant/homeassistant/components/google_maps/device_tracker.py", line 72, in _update_info
    for person in self.service.get_all_people():
  File "/usr/local/lib/python3.7/site-packages/locationsharinglib/locationsharinglib.py", line 439, in get_all_people
    people = self.get_shared_people() + [self.get_authenticated_person()]
  File "/usr/local/lib/python3.7/site-packages/locationsharinglib/locationsharinglib.py", line 400, in get_shared_people
    for info in output[0]:
TypeError: 'NoneType' object is not iterable

**Comment by costastf** [comment]
Please use the project mentioned above to get a valid cookie and in your hassio update your locationsharinglib to the latest version and provide it with the valid cookie that you will get in your workstation.

**Comment by costastf** [comment]
@NorthernMunkey I am guessing (hoping) that things worked for you since you did not respond back with more issues. Closing this for now, if there are more issues please comment back.
