### ISSUE TITLE
Only 1 devices showing - possible change on the Google side

### ISSUE THREAD

**Issue by jkempson** [costastf/locationsharinglib#62]
Hi I've been using locationsharinglib in my script for sometime without issue. I am using it to track 2 devices that share their location with a dedicated location sharing Google account. In the last week or so (maybe longer) it is only showing 1 of the devices. The other device isn't showing up. If I log in to this account using a browser I can see both devices perfectly.

Any ideas what could be causing the issue?

**Comment by jkempson** [comment]
Source code:
https://pastebin.com/ZLuX2AQN

Script runs every 10 minutes so I don't think I'll be violating any rate limits on Google. Also I've triggered this before and the whole thing fails not just 1 device.

FWIW I've also got a new cookie and changed IP.

**Comment by jkempson** [comment]
Looking at the debug output I'm getting:
DEBUG:locationsharinglib.Service:Missing essential info, cannot instantiate authenticated person
and
DEBUG:locationsharinglib.Service:Missing location or other info, dropping person with info:

But I can actually see the device listed in the debug output along with GPS coordinates so not sure what it thinks is missing?

**Comment by jkempson** [comment]
So for some reason, the device in question (Samsung S7) isn't reporting battery level.

If remove the "TypeError" from (from Person->_populate) so it looks like:
```
try:
    self._battery_level = data[13][1]
except:
    self._battery_level = None
```
everything works fine?

Data[13] for the device in question is returning
```
[0]
```

whilst the other functioning device is returning a value such as:

```
[1,50]
```

e.g. charging (1) and battery level 50%

Would removing the TypeError exception be an appropriate change to ensure devices not reporting battery are still useable?

**Comment by costastf** [comment]
Hi and thanks for all this debugging! I think that the best way forward would be to add an IndexError exception along with the TypeError one instead of removing the TypeError one. Like ```except (TypeError, IndexError):``` would you mind checking that out and reporting back it it fixes your issue so I can make the change and release a new version?

**Comment by liamsaliba** [comment]
Confirmed that 
```python
try:
    self._charging = data[13][0]
except (TypeError, IndexError):
    self._charging = None
try:
    self._battery_level = data[13][1]
except (TypeError, IndexError):
    self._battery_level = None
```
solves the above issue.

**Comment by costastf** [comment]
v4.0.2 released with the above fix.
