### ISSUE TITLE
Noob

### ISSUE THREAD

**Issue by dfawlt** [costastf/locationsharinglib#63]
I've got Hassio on a PI and access to macs and pcs.

Would it be easiest to run this from a mac to get the cookie and then put it on the pi?

Hassio doesn't seem to let you run python stuff.

**Comment by costastf** [comment]
Hi, sorry for the late reply! It should be very easy to run the mapscookiegettercli project from your mac, it has been tested for it, only I have not implemented support for safari, so it would work with firefox or chrome. Then you can move the cookie and use it with locationsharinglib.

**Comment by costastf** [comment]
I am closing this since it does not seem like a concrete issue, but if you have any problem or need any help please open it again.
