### ISSUE TITLE
Service does not seem to retrieve anything

### ISSUE THREAD

**Issue by WillDHB** [costastf/locationsharinglib#7]
When I instantiate the Service class, no data seems to be retrieved; e.g.:

>>>service.get_all_people()
()

I've considered that this may be related to my security settings; when I instantiate the service, I get a push notification on my phone asking if this is me (and I say yes).  I've also tried stealing my cookie jar from Firefox and dumping it to a file, then telling Service to use that file, but I get the same result - no error on instantiation, but no data, either.  Presumably it is not successfully logging on, but I'm not sure how to verify that yet.

**Comment by costastf** [comment]
This has to do with google security. One way to work around this, kinda, is to login to the tracking account through your browser so you can go through what ever challenge google sets and identify the device you are connecting from. Then while being logged in, try to connect through the library. It should hopefully be successful end it should also create a dump of the connection cookies that you can reuse to reconnect afterwards. I hope this makes sense and things work for you.

**Comment by costastf** [comment]
@WillDHB  did you get things working?

**Comment by WillDHB** [comment]
Yes; I stole the cookies from Firefox.  I had actually done this before and it hadn't worked, but I tried it with python3 and got everything going fine.  I'm guessing I just screwed up the process of getting the cookies before.

**Comment by JacobDB** [comment]
I'm having this same issue, very new to Python, not sure what needs to be done. I suspect it's returning blank due to 2FA.

**Comment by WillDHB** [comment]
It might be helpful to throw an exception for this type of problem.

@JacobDB Did you try the procedure mentioned above with regard to taking cookies from your browser?

**Comment by mitchellrj** [comment]
I found I had to enable this "Allow less secure apps" option in account settings to get it to work. Without this, the response from submitting the password was prompting to verify via phone (even with no phone number set on the account!)

<img width="1014" alt="screen shot 2018-09-29 at 22 23 44" src="https://user-images.githubusercontent.com/147070/46250624-94e34300-c436-11e8-919f-13fcbb60c8c2.png">

@costastf it would be great if you could document this somewhere, it was very tough to figure out. In the English response, a string to check for is "Verify that it's you".

**Comment by costastf** [comment]
Hi Richard,
I am sorry that this took so very long to respond to. It fell through the
cracks in a very busy period. It would be great if you could amend the
documentation the way you see fit to explain the problem and make an MR. I
will work on the library the coming week to try to handle the new
authentication that broke things and could use the help with the
documentation part :)

kind regards
Costas
