### ISSUE TITLE
service.get_all_people() not returning all shared persons

### ISSUE THREAD

**Issue by hemantkamalakar** [costastf/locationsharinglib#71]
Hi,
Thanks a lot for this library. It is really helpful.
I have setup a new Google account and shared location using Google Maps app with the new account. My wife also did the same. Using [locationsharing lib usage example](https://locationsharinglib.readthedocs.io/en/latest/usage.html) I can only see my wife's location. If i check in the Google Maps the new account shows both shared account.
What could be the issue?

**Comment by costastf** [comment]
Hi, thanks for the kind words! Please try to run it with debug on, it will probably be clear.

**Comment by costastf** [comment]
```
import logging
logging.basicConfig(level=logging.DEBUG)
```
Run the above before the snippet mentioned on the usage page. Please be careful it pasting the output as it will contain personal info.

**Comment by costastf** [comment]
Hi @hemantkamalakar any update?

**Comment by hemantkamalakar** [comment]
I managed to fix this issue by generating the new cookie on Ubuntu. The cookie generated on Windows 10 was only showing one person. Thanks again for writing such a great library. I am closing this issue now.

**Comment by AlejandroRivera** [comment]
FWIW, I had the same issue using the extension in Google Chrome called "[cookies.txt](https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg)", but no issues with the Firefox plugin called "[Export Cookies](https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg)".

**Comment by costastf** [comment]
ok, so apparently we have a matrix of success across OSes and plugins and the documentation of the project could benefit with the info. I would happily accept MRs that can fill in that matrix and save people time.

**Comment by nferreyra** [comment]
I was also dealing with this same issue when using the cookies collected with the Chrome plugin. After reading this and use Firefox with the [Export Cookies](https://addons.mozilla.org/en-US/firefox/addon/export-cookies-txt/) it just works!
Thanks for your work @costastf.
