### ISSUE TITLE
Is there a rate limit?

### ISSUE THREAD

**Issue by jpajenski** [costastf/locationsharinglib#72]
Hi, I'm trying to work around some issues with Home Assistant, so I set up your sample code (from the usage instructions to get the maps location) in a cron job to spit out my location data every 2 minutes. This ran fine several times, but now I have no output and no errors. Is there a rate limit on the google side?

**Comment by costastf** [comment]
Hi @jpajenski , no there is no rate limit, but google has a lot of fraudulent traffic identification methods and if they think you are doing something wrong they will temporarily blacklist you and the process will be presented with a captcha which of course is not visible so it will just stop refreshing the info until the temporary blacklist is lifted. What could be identified as fraudulent traffic for example could be you using the same account for which you use a cookie from another device in your network.

**Comment by jpajenski** [comment]
Thanks, you're right I never turned off home assistant and it started working when mine broke.
