### ISSUE TITLE
More precisions about "get-maps-cookies"

### ISSUE THREAD

**Issue by guillaumecardon** [costastf/locationsharinglib#76]
Hello,

I'm reading doc about installation and usage of your library.
Unfortunetaly, i think it miss some parts to understand how the library works.

In this page : https://locationsharinglib.readthedocs.io/en/latest/usage.html we see 
`cookies_file = 'FILE_CREATED_BY_MAPSCOOKIEGETTERCLI_AUTHENTICATION_PROCESS'`

What is this "cookie file" ? 
After some searches in "closed issues" section, we need to use "get-maps-cookies" but what is it ? Where is documentation about this ?

Thanks for your help  :-)

**Comment by linuxnico** [comment]
i find this:
https://pypi.org/project/mapscookiegettercli/

**Comment by costastf** [comment]
Hi, apologies for missing this issue, I did not get a notification for it. The documentation needs updating. The cookie file mentioned is a file from a browser extension after you successfully log in interactively with your credentials in Google maps. Hope that helps in clarifying.

**Comment by guillaumecardon** [comment]
Thanks for your answers.
After some searches, i found the previous link given by linuxico.
Thanks to that, i discover i need python3.7.. and a graphical browser...

I think it was easy to get google sharing location on my raspberry headless... and finally, i need to install a third party library on another OS ... 😄 

It doesn't really matter, but it's confusing compared to initial readme of locationsharinglib 😉

**Comment by costastf** [comment]
Hi, you do not need a browser on your raspberry and it is easy to get it
running, but you do need Python 3.7. you can extract the cookies from any
computer and provide them to the library.
https://www.home-assistant.io/integrations/google_maps/ documents how the
component is set up for home Assistant but the directions are the same up
until you get a valid cookie file. That is what you need to provide to the
library. I hope this helps. If you need more details please let me know.
