### ISSUE TITLE
SyntaxError: invalid Syntax in "domain: str"

### ISSUE THREAD

**Issue by emilyboda** [costastf/locationsharinglib#79]
I'm getting the following error:

```
pi@pi:~/google-maps-location-files $ python3 get-location.py                    Traceback (most recent call last):
  File "get-location.py", line 1, in <module>
    from locationsharinglib import Service
  File "/home/pi/.local/lib/python3.5/site-packages/locationsharinglib/__init__.py", line 36, in <module>
    from .locationsharinglib import Service, Person
  File "/home/pi/.local/lib/python3.5/site-packages/locationsharinglib/locationsharinglib.py", line 75
    domain: str
          ^
SyntaxError: invalid syntax

```

- I am using Python 3.5.3.
- I installed locationsharinglib by "pip3 install locationsharinglib"
- I believe my cookies file is good. I have downloaded it using cookies.txt on Chrome and then I tried again later using the Firefox download cookies extension.

My file get-location.py is as follows:

```
from locationsharinglib import Service
cookies_file = '/home/pi/google-maps-location-files/.google_maps_location_sharing.cookies.MYEMAILADDRESS_gmail_com'
google_email = 'MYEMAILADDRESS@gmail.com'
service = Service(cookies_file=cookies_file, authenticating_account=google_email)
for person in service.get_all_people():
    print(person)
```

Can anyone help me understand what I'm doing wrong?

[My cookies file looks like this. Is this correct?](https://photos.app.goo.gl/sd8SXkEu1VYcnhMe9) I will remove the link to the cookies file soon because I am not totally sure what information about it can be used against me...

**Comment by costastf** [comment]
Please remove your cookie file, if it is correct anyone can use it to log in to your services.

**Comment by costastf** [comment]
The issue you are having is because you are using python 3.5 . There code uses dataclasses which are a feature of python 3.7. there is a dataclasses package that can be installed for 3.6 but honestly there is no point.

**Comment by costastf** [comment]
I suggest you use pyenv if you are on a *nix system and install 3.7 and everything will work just fine. Apologies for not answering earlier but I did not get a notification about the issue being opened.

**Comment by costastf** [comment]
Just saw that you have blurred your cookie file, so you are good :) I will be closing this since it is not an issue but if you need any help please don't hesitate to add a comment.
