### ISSUE TITLE
Accuracy is parsed wrong

### ISSUE THREAD

**Issue by michaelarnauts** [costastf/locationsharinglib#8]
The field that is currently is extracted as accuracy is not the real accuracy. Google maps pinned me exact on the location where I am, but the lib is reporting an accuracy of 1500.

**Comment by costastf** [comment]
I was actually shooting blind, so it makes sense... :( i will revert the accuracy.

**Comment by costastf** [comment]
reverted in v1.0.0

**Comment by michaelarnauts** [comment]
Why is this issue closed? I guess it would make sense to keep issues open as long as they are not resolved. 

The accuracy field should be in the data somewhere since maps can show it.

**Comment by costastf** [comment]
I closed it because I removed the wrong accuracy field, so this is
resolved. Not the way we would want but I have no clue which field it
could  be so I would just be guessing again.

**Comment by michaelarnauts** [comment]
Okay, but maybe somebody else wants to look into this, and they could see that this is something that needs to be done? This is what open source is about right?

**Comment by costastf** [comment]
Excellent point! It wasn't meant to defer any development on this :)

**Comment by costastf** [comment]
I re exposed the accuracy field on v.1.2. I am closing this issue since there was no new info on it. If we get anything new, we can just re open.
