### ISSUE TITLE
Requirement is pinned for locationsharinglib 4.1.0: requests~=2.21.0

### ISSUE THREAD

**Issue by MartinHjelmare** [costastf/locationsharinglib#81]
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

**Comment by MartinHjelmare** [comment]
@costastf Hi! Sorry to ping you. Did you see this issue?

**Comment by costastf** [comment]
omg @MartinHjelmare thanks for pinging! I had not seen this, the notifications dropped the ball. Would pinning like this ```>=2.20.0,<3.0``` be ok? If so, i can make a new patch version asap. And by the way, happy new year!

**Comment by costastf** [comment]
Loosened up the pinning to >= for all dependencies and v4.1.4 should solve the issue. Please let me know it there is anything else i can do.

**Comment by MartinHjelmare** [comment]
Thanks for working on this! I don't see the loosening of the versions when looking at the release diff:
https://github.com/costastf/locationsharinglib/compare/4.0.2...4.1.4

**Comment by costastf** [comment]
Hm... Let me have a look, did it this morning and probably was not wake enough.

**Comment by costastf** [comment]
Forgot to push, released version should have the right files... new years morning... probably should not release software after the New Year's night.

**Comment by MartinHjelmare** [comment]
Thanks! If you have time it would be good to release a new version so that the github tag and PyPI release are in sync. This makes it easier for the community to follow the development.

**Comment by costastf** [comment]
Sure, fair point, will do so in a couple of hours, thanks!

**Comment by costastf** [comment]
v4.1.5 should align things. Unless I screwed up again :) Hopefully not. :)

**Comment by MartinHjelmare** [comment]
Awesome! Thanks and Happy New Year!

**Comment by costastf** [comment]
Thank you for pinging me and bringing this to my attention and for your patience! Happy New year!
