### ISSUE TITLE
Authenticated but error 404

### ISSUE THREAD

**Issue by tyjtyj** [costastf/locationsharinglib#87]
Something just changed on google ? 
I got authenticated but error 404. I tried new cookies files and different account giving same error

```
2021-04-09 20:34:53 DEBUG (SyncWorker_2) [locationsharinglib.Service] Validating access to personal account...
2021-04-09 20:34:53 DEBUG (SyncWorker_2) [locationsharinglib.Service] <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>


  <p>The requested URL <code>/maps/preview/locationsharing/read?authuser=0&amp;hl=en&amp;gl=us&amp;pb=%211m7%218m6%2
<truncated>
i4111425</code> was not found on this server.  <ins>That’s all we know.</ins>
```

2021-04-09 20:34:53 WARNING (SyncWorker_2) [locationsharinglib.Service] Received response code:404

**Comment by tyjtyj** [comment]
Check the debug log found network trace. seems my country change to this url
from
`url = 'https://www.google.com/maps/preview/locationsharing/read'`
to
`url = 'https://www.google.com/maps/rpc/locationsharing/read'`

I still get issue in debug but it working now

`DEBUG (SyncWorker_13) [locationsharinglib.Service] Missing essential info, cannot instantiate authenticated person`

let me know if you need more information

**Comment by costastf** [comment]
Hi @tyjtyj , thanks a lot for filling an issue and doing some debugging. I am currently away and will be back in a couple of days so will make a fix for it. If it happened to you I am expecting this to happen everywhere pretty soon. Thanks again!

**Comment by tyjtyj** [comment]
I saw this was patch back april 2020
not sure why it is happening for me now.. still checking 

https://github.com/costastf/locationsharinglib/commit/931713fe31588008bb8634d96342ed512cbaf47d#diff-99a505d83edfb3a9c7c06eff107d4b76953c3699e7f1688d734fc412238b999a

**Comment by tyjtyj** [comment]
Closing this as some bug in my python version... isolated issue.
