### ISSUE TITLE
Guide on how to save cookie?

### ISSUE THREAD

**Issue by zefoo** [costastf/locationsharinglib#92]
Howdy, this looks like the only option to pull location via google maps. I'm not sure if this is from my account that is sharing location to other people or is it the recipient email that I share a location with? 

Also, is there any guide on how to save cookie? Or which one? I'm looking at Inspector -> Storage -> Cookies but there are a handful of different ones. 

I assume this is still works. Thank you!

**Comment by costastf** [comment]
Hi @zefoo . This needs the account that you are sharing your locations to from other accounts. You can use https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid for chrome or https://github.com/rotemdan/ExportCookies for firefox. This still works indeed. Have a great day!

**Comment by zefoo** [comment]
Hey costastf, super appreciate your fast message. I just found that and actually just came back in here to report my findings. :) 

I go to the email I got from google immediately after share, subject: "See foo's real-time location on Google Maps"

Then I click on "View on Google Maps"

I login. I export with Chrome's get-cookies.txt. I follow https://locationsharinglib.readthedocs.io/en/latest/usage.html and feed the full path of the cookies file. As well as my email (I tried both a google apps account and a personal @gmail account). I get this error:

InvalidCookies: The cookies provided do not provide a valid session, could not reach personal account page.Please create another cookie file and try again.

I've went through this process a few times now. Am I doing something incorrectly?

Thank you!

**Comment by costastf** [comment]
You are just lucky i just woke up and i had some time before i have to leave :) This has been designed over personal gmail accounts. I have not tested this with any other of the possible offerings for accounts. I have created a tracker.account@gmail.com for instance (not acctual email) and share my location from my personal account to that. Then you need to log in with your tracker.account@gmail.com and get the cookies for that. I hope this helps. If it does not, please enable debug logging to see if there is anything there. Please be mindful when pasting any debugging output as to not share any personal info, although i hope you won't need to :)
