### ISSUE TITLE
Guide on how to save cookie? (2)

### ISSUE THREAD

**Issue by zefoo** [costastf/locationsharinglib#93]
Not sure if my previous post went through and/or if notification was sent?

Reference: #92 

Hey costastf, super appreciate your fast message. I just found that and actually just came back in here to report my findings. :)

I go to the email I got from google immediately after share, subject: "See foo's real-time location on Google Maps"

Then I click on "View on Google Maps"

I login. I export with Chrome's get-cookies.txt. I follow https://locationsharinglib.readthedocs.io/en/latest/usage.html and feed the full path of the cookies file. As well as my email (I tried both a google apps account and a personal @gmail account). I get this error:

InvalidCookies: The cookies provided do not provide a valid session, could not reach personal account page.Please create another cookie file and try again.

I've went through this process a few times now. Am I doing something incorrectly?

Thank you!

**Comment by costastf** [comment]
You are just lucky i just woke up and i had some time before i have to leave :) This has been designed over personal gmail accounts. I have not tested this with any other of the possible offerings for accounts. I have created a tracker.account@gmail.com for instance (not acctual email) and share my location from my personal account to that. Then you need to log in with your tracker.account@gmail.com and get the cookies for that. I hope this helps. If it does not, please enable debug logging to see if there is anything there. Please be mindful when pasting any debugging output as to not share any personal info, although i hope you won't need to :)

ps: responded on the initial issue and just copy pasted the response here also in case you missed the other one.

**Comment by zefoo** [comment]
I was using Incognito. It worked without Incognito. Thank you. :) How long does this cookie last for before I need to do this again?

**Comment by costastf** [comment]
it should not expire, unless you log out of the session from the browser. I think i can close this now?

**Comment by zefoo** [comment]
Thanks for confirming before closing. 

Maybe last question. :) Is there any limit to how many users can share their location? I'm wanting to use this to help a non-profit. Thank you!

**Comment by zefoo** [comment]
Oh, and second question - have you seen any issues if I pull location every 10 minutes? Any concern about getting blacklisted? Thank you thank you!

**Comment by costastf** [comment]
I don't know, I guess you can look that up on the Google documentation
about location sharing.

**Comment by zefoo** [comment]
Ok, thanks!

**Comment by costastf** [comment]
Oh, I missed this question. No there is no problem, the UI queries the
location every 30 seconds so there will be no problem.
