### ISSUE TITLE
SUGGESTION: Implement service.get_timestamp_by_nickname('NICKNAME')

### ISSUE THREAD

**Issue by frickypickle** [costastf/locationsharinglib#95]
Like the titles says, this would enable the ability to get info on the last time the location was located. This would be very useful since sometimes google maps can have delays of up to 3 hours before the location finally updates.

**Comment by costastf** [comment]
Hi @eclipsek20 , thanks for the suggestion. Any chance you might want to give the implementation a try yourself and make an MR for it? It would basically be a small refactor of https://github.com/costastf/locationsharinglib/blob/main/locationsharinglib/locationsharinglib.py#L234

**Comment by frickypickle** [comment]
@costastf well whilst I was writing this I wasn't aware of how easy it was to implement my own implementation, I added the time and other stuff. Anyway thanks for the answer!

**Comment by costastf** [comment]
Will you make an MR with those changes so others can benefit from your work?

**Comment by frickypickle** [comment]
I will try but I can not guarantee anything.

**Comment by costastf** [comment]
If you need any help, please let me know.

**Comment by frickypickle** [comment]
Okay I have no clue what I done but I did something? I hope I correctly submitted it.
