### ISSUE TITLE
I am not getting authenticated, did google change something?

### ISSUE THREAD

**Issue by chagai95** [costastf/locationsharinglib#97]
I just noticed today and I tried two different accounts already that used to work:
service.get_authenticated_person()
is giving me a None

**Comment by costastf** [comment]
Hi, thanks for reporting. Can you please elaborate a bit? Are you authenticating via the browser, exporting the cookies, passing them to the library and you are not getting anything? Because the way I read it might be that you are trying to use existing cookies that worked but no longer do. Which is the case? Also, can you please supply a debug log, being careful to remove any personal info so I can see what happens?

**Comment by chagai95** [comment]
Hey, thx for answering!  I am getting a new cookies file from the browser I'll try getting a debug log now

**Comment by chagai95** [comment]
I'm sorry for the noob question, but how do I get the logs? I changed the logging level I think but I have no idea where the logs are...

**Comment by costastf** [comment]
`
import logging
logging.basicConfig(level=logging.DEBUG)
`
right before any other code
Formatting is not right, you need a new line between the statements

**Comment by costastf** [comment]
Please make sure you don't upload any personal or sensitive info

**Comment by chagai95** [comment]
It's a test account so I don't mind if it helps to just upload everything, not sure what is sensitive and what is not:

```
DEBUG:locationsharinglib.Service:Creating person for authenticated account with email whereischagai@gmail.com                                                     

DEBUG:locationsharinglib.Service:Missing essential info, cannot instantiate authenticated person whereischagai@gmail.com: list index out of range      
```

Is this the same error that comes when the caches are wrong?

**Comment by chagai95** [comment]
Ok I think the problem was with Get cookies extension because I just logged in from another browser and got the cookies from there and it worked, sorry for bothering, thx again!

**Comment by costastf** [comment]
No, but this is not an error per se, it might be normal to not be able to get the authenticated person details. Do you not see the shared accounts though? What does the debug show when you try to iterate over the shared accounts?

**Comment by costastf** [comment]
👍

**Comment by costastf** [comment]
Glad it worked out😊
